#!/bin/bash
# curl -XPUT http://search-shakespeare-mnwcg7u4k7pdl4a2rtqp2whufm.eu-west-1.es.amazonaws.com/shakespeare -d '
# {
#  "mappings" : {
#   "_default_" : {
#    "properties" : {
#     "speaker" : {"type": "string", "index" : "not_analyzed" },
#     "play_name" : {"type": "string", "index" : "not_analyzed" },
#     "line_id" : { "type" : "integer" },
#     "speech_number" : { "type" : "integer" }
#    }
#   }
#  }
# }
# ';
#
#curl -XPUT http://elasticsearch23.ttd.persgroep.digital:9200/_bulk --data-binary @shakespeare.json
curl -XPUT http://elasticsearch23.ttd.persgroep.digital:9200/_snapshot/shakespeare -d '
{
  "type": "s3",
  "settings": {
    "bucket": "es-snapshots-ttd-persgroep-digital",
    "region": "eu-west",
    "base_path": "elasticsearch23-ttd-persgroep-digital"
  }
}'
# import boto3
# import json
# import subprocess
# import time
#
# cmd = "curl -XDELETE http://search-shakespeare-mnwcg7u4k7pdl4a2rtqp2whufm.eu-west-1.es.amazonaws.com/shakespeare/"
# subprocess.call(cmd,shell=True)
