#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update <SSH_KEYNAME> <DNSDOMAIN> <VPCID>"
  echo "e.g. $0 create MyAWSKey example.com vpc-3ab76351"
  exit 1
else
  # Sets $IPADDRESS as your external IP (for AWS Security Groups)
  IPADDRESS=`wget -qO- http://ipecho.net/plain ; echo -n`
  
  # We need a unique "stackname" for CloudFormation,
  # however CF doesn't accept periods in stack-names
  STACK_NAME=`echo $3 | sed -e 's/\./\-/g'`

  # Configures the aws-cli - requires an access key id and secret
  # http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
  export AWS_DEFAULT_PROFILE=elasticsearch-$STACK_NAME
  aws configure --profile $AWS_DEFAULT_PROFILE
  
  # Run the CF command with our parameters and the template.json
  aws cloudformation $1-stack \
    --stack-name $AWS_DEFAULT_PROFILE \
    --template-body file://template.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=SSHLocation,ParameterValue="$IPADDRESS/32" \
ParameterKey=KeyName,ParameterValue=$2 \
ParameterKey=DNSDomain,ParameterValue=$3 \
ParameterKey=VpcId,ParameterValue=$4
fi
